fuzzy_match <- function(typo_list){
  #takes in column vector of department names
  #outputs column vector of matched names
  #crosswalks dept codes to dept names
  
  # --------------- define names to match to --------------------------------
  
  department_names <- c( 
    #UCSD departments
    "Academic Internship Program",
    "Alumni",
    "Anthropology",
    "Archaeology",
    "Art History",
    "Bioengineering",
    "Biological Sciences",
    "Biology", "Marine Biology", "Human Biology",
    "Biochemistry",
    "CAT (Sixth College)",
    "Chemistry",
    "Chinese Studies",
    "Classical Studies",
    "Cognitive Science",
    "Communication",
    "Computer Science",
    "Critical Gender Studies",
    "Dance",
    "Data Science",
    "Economics",
    "Education Studies",
    "Electrical & Computer Engineering",
    "English",
    "Engineering",
    "Environmental Systems",
    "Ethnic Studies",
    'Extension',
    "First Year Experience",
    "Film Studies",
    "Geosciences",
    "General",
    "German Studies",
    "Global Health",
    "Global Policy and Strategy",
    "Public Health",
    "History",
    'Human Development Sciences',
    "International Studies",
    "Italian Studies",
    "Japanese Studies",
    "Jewish Studies",
    "Latin American Studies",
    "Library staff",
    "Linguistics",
    "Literature",
    "Mathematics",
    "Medicine",
    "Mechanical & Aerospace Engineering",
    "Music",
    "Music Department",
    "Nanoengineering",
    "Office for Equity, Diversity & Inclusion",
    "Pharmacy",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Pyschiatry",
    "Rady School of Management",
    "Religion",
    "Russian and Soviet Studies",
    "Scripps Institute of Oceanography",
    "School of Medicine",
    "Sociology",
    "Spanish",
    "Structural Engineering",
    "Teaching and Learning Commons",
    "Theatre and Dance",
    "Urban Studies and Planning",
    "Visual Arts",
    
    #dept codes
    "ANTH",
    "BENG",
    "BIOL",
    "CAT",
    "CENG",
    "CGS",
    "CHEM",
    "CHIN",
    "COGS",
    "COMM",
    "CONT",
    "CSE",
    "DOC",
    "DSC",
    "ECE",
    "ECON",
    "EDS",
    "ENVR",
    "ERC",
    "ESYS",
    "ETHN",
    "FILM",
    "FPMU",
    "GPS",
    "HDP",
    "HDS",
    "HDSI",
    "HIST",
    "HMNR",
    "HUM",
    "ICAM",
    "INTL",
    "JAPN",
    "JUDA",
    "LATI",
    "LAWS",
    "LING",
    "LIT",
    "MAE",
    "MATH",
    "MMW",
    "MUIR",
    "MCWP",
    "MUS",
    "MGMT",
    "NENG",
    "NANO",
    "POLI",
    "PHIL",
    "PHYS",
    "PSYC",
    "RELI",
    "REV",
    "RSM",
    "SE",
    "SIO",
    "SOC",
    "SOE",
    "STPA",
    "SXTH",
    "SUNY",
    "THEA",
    "TMC",
    "TWS",
    "USP",
    "VIS",
    "WARR",
    "WCWP",
    
    #UCSD colleges
    "Muir",
    "Marshall",
    "Warren",
    "Revelle",
    "ERC", "Roosevelt", 
    "Sixth",
    "Seventh",
    
    #institutions
    "SDSU",
    "SJSU",
    "USD",
    "UCSD Extension",
    "UCLA",
    "SDSC",
    
    #Health
    "Family Medicine",
    "Gastroenterology",
    "Health Strategy",
    "Neurology",
    "Neurosciences",
    "Nursing",
    "Pathology",
    "Radiology",
    "Shiley Eye Institute",
    "UCSD Health",
    "VA Nurse",
    "Infectious disease",
    
    #other (these are not ordered)
    "MPP", #master public policy
    "Off Campus",
    "non-UCSD",
    "San Diego Supercomputer Center",
    "SDCWA", #San Diego County Water Authority
    "Other",
    "NOAA - Southwest Fisheries Science Center",
    "NOAA - SWFSC", #same as previous obs
    "Center for Gender Equity & Health",
    "Triton Tree Trust",
    "Campus Planning",
    "HDSI",
    "HDS", #Human Development Sciences 
    "ACTRI",
    "Calit2",
    "JSOE",
    "Career Center",
    "HILA",
    "SSPPS",
    "Public",
    "Statistics",
    "GLBH",
    "ANP",
    "Korea",
    "LAS",
    "Community Member",
    "Center for U.S.-Mexican Studies",
    "DOC Writing Program",
    "Visiting Scholar"
  )
  
  
  ## ------------------------ FUZYY MATCHING  -------------------
  
  indices <- stringdist::amatch(x = typo_list, #things we want matched 
                    table = department_names, #table of correct names
                    method = "jw", #jaro winkler methodology
                    maxDist = 0.3 #unsure ideal dist.
                    #strict seems better since our dict is so big 
                    )
  ## assign to new obj
  matched_departments <- department_names[indices]
  
  # ----------------- CROSSSWALK ------------------------------------
  
  #crosswalk dept codes to dept names
  crosswalk_list <- list(
    "ANTH" = "Anthropology",
    "BENG" = "Bioengineering",
    "BIOL" = "Biology",
    "CAT" = "Culture, Art, & Technology",
    "CENG" = "Chemical Engineering",
    "CGS" = "Critical Gender Studies",
    "CHEM" = "Chemistry",
    "CHIN" = "Chinese Studies",
    "COGS" = "Cognitive Science",
    "COMM" = "Communication",
    "CONT" = "Contemporary Issues",
    "CSE" = "Computer Science",
    "DOC" = "DOC Writing Program",
    "DSC" = "Data Science",
    "ECE" = "Electrical & Computer Engineering",
    "ECON" = "Economics",
    "EDS" = "Education Studies",
    "ENVR" = "Environmental Systems",
    "ERC" = "Eleanor Roosevelt College",
    "ESYS" = "Environmental Systems",
    "ETHN" = "Ethnic Studies",
    "FILM" = "Film Studies",
    "GPS" = "Global Policy and Strategy",
    "HDP" = "Human Development Sciences",
    "HIST" = "History",
    "HDS" = "Human Development Sciences",
    "HDSI" = "Data Science",
    "HMNR" = "Human Rights and Migration",
    "HUM" = "Humanities",
    "ICAM" = "Visual Arts",
    "INTL" = "international Studies",
    "JAPN" = "Japanese Studies",
    "JUDA" = "Jewish Studies",
    "LATI" = "Latin American Studies",
    "LAWS" = "Law and Society",
    "LING" = "Linguistics",
    "LIT" = "Literature",
    "MAE" = "Mechanical & Aerospace Engineering",
    "MATH" = "Mathematics",
    "MMW" = "MMW",
    "MUIR" = "Muir College",
    "MCWP" = "Muir College Writing Program",
    "MUS" = "Music",
    "Music Department" = "Music",
    "MGMT" = "Rady School of Management",
    "NANO" = "Nanoengineering",
    "NENG" = "Nanoengineering", #NANO and NENG are both nanoengineering
    "POLI" = "Political Science",
    "PHIL" = "Philosophy",
    "PHYS" = "Physics",
    "PSYC" = "Psychology",
    "RELI" = "Religion",
    "REV" = "Revelle College",
    "RSM" = "Rady School of Management",
    "SE" = "Structural Engineering",
    "SIO" = "Scripps Institute of Oceanography",
    "SOC" = "Sociology",
    "SOE" = "School of Engineering",
    "STPA" = "Science, Technology, and Public Affairs",
    "SXTH" = "Sixth College",
    "THEA" = "Theatre and Dance",
    "TMC" = "Marshall College",
    "TWS" = "Third World Studies",
    "USP" = "Urban Studies and Planning",
    "VIS" = "Visual Arts",
    "WARR" = "Warren College",
    "WCWP" = "Warren College Writing Program"
  )
  
  #loop through both lists and crosswalk
  for(i in names(crosswalk_list)){
    matched_departments[matched_departments == i] <- crosswalk_list[[i]]
  }
  #abbreviations to their full names
  matched_departments[matched_departments == "NOAA - SWFSC"] <- "NOAA - Southwest Fisheries Science Center"
  matched_departments[matched_departments == "SDSC"] <- "San Diego Supercomputer Center"
  matched_departments[matched_departments == "Extension"] <- "UCSD Extension"
  
  # --------------------- RETURN MATCHED DEPARTMENTS ------------------------
  
  return(matched_departments)
}
