library(stringdist)
library(dplyr)

#define department names to match to
department_names <- c( #UCSD departments
                      "Aerospace Engineering",
                      "Academic Internship Program",
                      "Alumni",
                      "Anthropology",
                      "Archaeology",
                      "Art History",
                      "Bioengineering",
                      "Biological Sciences",
                      "Biology",
                      "Biochemistry",
                      "CAT (Sixth College)",
                      "Chemistry",
                      "Chinese Studies",
                      "Classical Studies",
                      "Cognitive Science",
                      "Communication",
                      "Computer Science",
                      "Critical Gender Studies",
                      "Dance",
                      "Data Science",
                      "Economics",
                      "Education Studies",
                      "Electrical & Computer Engineering",
                      "English",
                      "Engineering",
                      "Environmental Systems",
                      "Ethnic Studies",
                      'Extension',
                      "First Year Experience",
                      "Geosciences",
                      "General",
                      "German Studies",
                      "Global Health",
                      "Global Policy and Strategy",
                      "Public Health",
                      "History",
                      'Human Development Sciences',
                      "International Studies",
                      "Italian Studies",
                      "Japanese Studies",
                      "Jewish Studies",
                      "Latin American Studies",
                      "Library staff",
                      "Linguistics",
                      "Literature",
                      "Mathematics",
                      "Medicine",
                      "Mechanical Engineering",
                      "Music",
                      "Nanoengineering",
                      "Nursing",
                      "Office for Equity, Diversity & Inclusion",
                      "Pharmacy",
                      "Philosophy",
                      "Physics",
                      "Political Science",
                      "Psychology",
                      "Pyschiatry",
                      "Rady School of Management",
                      "Religion",
                      "Russian and Soviet Studies",
                      "Scripps Institute of Oceanography",
                      "School of Medicine",
                      "Sociology",
                      "Spanish",
                      "Structural Engineering",
                      "Teaching and Learning Commons",
                      "Theatre and Dance",
                      "UCSD Health",
                      "Urban Studies and Planning",
                      "Visual Arts",
                      
                      #dept codes
                      "ANTH",
                      "BENG",
                      "BIOL",
                      "CAT",
                      "CENG",
                      "CGS",
                      "CHEM",
                      "CHIN",
                      "COGS",
                      "COMM",
                      "CONT",
                      "CSE",
                      "DOC",
                      "DSC",
                      "ECE",
                      "ECON",
                      "EDS",
                      "ENVR",
                      "ERC",
                      "ESYS",
                      "ETHN",
                      "FILM",
                      "FPMU",
                      "GPS",
                      "HDP",
                      "HIST",
                      "HMNR",
                      "HUM",
                      "ICAM",
                      "INTL",
                      "JAPN",
                      "JUDA",
                      "LATI",
                      "LAWS",
                      "LING",
                      "LIT",
                      "MAE",
                      "MATH",
                      "MMW",
                      "MUIR",
                      "MCWP",
                      "MUS",
                      "MGMT",
                      "NENG",
                      "NANO",
                      "POLI",
                      "PHIL",
                      "PHYS",
                      "PSYC",
                      "RELI",
                      "REV",
                      "RSM",
                      "SE",
                      "SIO",
                      "SOC",
                      "SOE",
                      "STPA",
                      "SXTH",
                      "SUNY",
                      "THEA",
                      "TMC",
                      "TWS",
                      "USP",
                      "VIS",
                      "WARR",
                      "WCWP",
                      
                      #UCSD colleges
                      "Muir",
                      "Marshall",
                      "Warren",
                      "Revelle",
                      "ERC", "Roosevelt", 
                      "Sixth",
                      "Seventh",
                      
                      #institutions
                      "SDSU",
                      "SJSU",
                      "USD",
                      "UCSD Extension",
                      "UCLA",
                      
                      #Health
                      "Family Medicine",
                      "Gastroenterology",
                      "Health Strategy",
                      "Neurology",
                      "Neurosciences",
                      "Pathology",
                      "Radiology",
                      "Shiley Eye Institute",
                      "VA Nurse",
                      "Infectious disease",
                      
                      #other (these are not ordered)
                      "MPP", #master public policy
                      "Off Campus",
                      "non-UCSD",
                      "SDSC",
                      "SDCWA", #San Diego County Water Authority
                      "Other",
                      "NOAA - Southwest Fisheries Science Center",
                      "NOAA - SWFSC", #same as previous obs
                      "Center for Gender Equity & Health",
                      "Triton Tree Trust",
                      "Campus Planning",
                      "HDSI",
                      "HDS", #Human Development Sciences 
                      "ACTRI",
                      "Calit2",
                      "JSOE",
                      "Career Center",
                      "HILA",
                      "SSPPS",
                      "Public",
                      "Statistics",
                      "GLBH",
                      "ANP",
                      "Korea",
                      "LAS",
                      "Community Member",
                      "Center for U.S.-Mexican Studies"
                      )

#function to be called in server.R
fuzzy_match <- function(typo_list){
  
  #amatch from stringdist::
  indices <- amatch(x = typo_list, #things we want matched / regularized
                    table = department_names, #table of correct names
                    method = "jw", #jaro winkler methodology
                    maxDist = 0.25 #unsure ideal dist.
                    #strict seems better since our dict is sobig and based on 
                    #which departments already exist in the data
                    )
  
  ## assign to new obj
  matched_departments <- department_names[indices]
  return(matched_departments)
}
