library(stringdist)
library(dplyr)

#define department names to match to
department_names <- c(
                        #department names
                      "Aerospace Engineering",
                      "Academic Internship Program",
                      "Alumni",
                      "Anthropology",
                      "Archaeology",
                      "Bioengineering",
                      "Biological Sciences",
                      "Biochemistry",
                      "CAT (Sixth College)",
                      "Chemistry",
                      "Chinese Studies",
                      "Classical Studies",
                      "Cognitive Science",
                      "Communication",
                      "Computer Science",
                      "Critical Gender Studies",
                      "Dance",
                      "Data Science",
                      "Economics",
                      "Education Studies",
                      "Electrical & Computer Engineering",
                      "English",
                      "Environmental Systems",
                      "Ethnic Studies",
                      'Extension',
                      "First Year Experience",
                      "Geosciences",
                      "German Studies",
                      "Global Health",
                      "Global Policy and Strategy",
                      "Public Health",
                      "History",
                      'Human Development Sciences',
                      "International Studies",
                      "Italian Studies",
                      "Japanese Studies",
                      "Jewish Studies",
                      "Latin American Studies",
                      "Library staff",
                      "Linguistics",
                      "Literature",
                      "Mathematics",
                      "Medicine",
                      "Mechanical Engineering",
                      "Music",
                      "Nanoengineering",
                      "Nursing",
                      "Office for Equity, Diversity & Inclusion",
                      "Pharmacy",
                      "Philosiphy",
                      "Physics",
                      "Political Science",
                      "Psychology",
                      "Rady School of Management",
                      "Religion",
                      "Russian and Soviet Studies",
                      "Scripps Institute of Oceanography",
                      "School of Medicine",
                      "Sociology",
                      "Structural Engineering",
                      "Teaching and Learning Commons",
                      "Theatre and Dance",
                      "UCSD Health",
                      "Urban Studies and Planning",
                      "Visual Arts",
                      
                      #dept codes
                      
                      "ANTH",
                      "BENG",
                      "BIOL",
                      "CAT",
                      "CENG",
                      "CGS",
                      "CHEM",
                      "CHIN",
                      "COGS",
                      "COMM",
                      "CONT",
                      "CSE",
                      "DOC",
                      "DSC",
                      "ECE",
                      "ECON",
                      "EDS",
                      "ENVR",
                      "ERC",
                      "ESYS",
                      "ETHN",
                      "FILM",
                      "FPMU",
                      "GPS",
                      "HDP",
                      "HIST",
                      "HMNR",
                      "HUM",
                      "ICAM",
                      "INTL",
                      "JAPN",
                      "JUDA",
                      "LATI",
                      "LAWS",
                      "LING",
                      "LIT",
                      "MAE",
                      "MATH",
                      "MMW",
                      "MUIR",
                      "MCWP",
                      "MUS",
                      "MGMT",
                      "NENG",
                      "POLI",
                      "PHIL",
                      "PHYS",
                      "PSYC",
                      "RELI",
                      "REV",
                      "RSM",
                      "SE",
                      "SIO",
                      "SOC",
                      "SOE",
                      "STPA",
                      "SXTH",
                      "THEA",
                      "TMC",
                      "TWS",
                      "USP",
                      "VIS",
                      "WARR",
                      "WCWP",
                      
                      #other
                      "MPP", #master public policy
                      "Off Campus",
                      "non-UCSD",
                      "SDSC",
                      "SDCWA", #San Diego County Water Authority
                      "SDSU",
                      "USD"
                      )

#function to be called in server.R
fuzzy_match <- function(typo_list){
  
  #amatch from stringdist::
  indices <- amatch(x = typo_list, #things we want matched / regularized
                    table = department_names, #table of correct names
                    method = "jw", #jaro winkler methodology
                    maxDist = 0.25 #unsure ideal dist, 0.5 seemed worse
                    )
  
  ## assign to new obj
  matched_departments <- department_names[indices]
  
  return(matched_departments)
}
